### ISSUE TITLE
Not transforming Ruby input file

### ISSUE THREAD

**Issue by hendrikstier** [Ennosuke/Normalize-Indentation#2]
I'm trying to apply the normalization to the following file:

``` ruby
# a class for O
class O < SomeClass
  def pp
    puts "hello"
  end
end

o = O.new
o.pp
```

Line 4 contains a tab (or in another test: 2 spaces). I would expect the script to replace the tab with the appropriate number of spaces (4) in both cases, but the console output reads:

```
Starting to normalize indentation
all is fine and dandy
Done normalizing indentation
```

What could be the reason for this? Could you please advise me on where to start debugging?

**Comment by Ennosuke** [comment]
Hey, could you provide me a file with which the problem occurs? I can partly reproduce the error but not reliable. Also what are your settings in the language specific settings? Did you set "translate_tabs_to_spaces" and "tab_size" to true and 4 ?

``` javascript
{
"tab_size": 4,
"translate_tabs_to_spaces": true
}
```

**Comment by hendrikstier** [comment]
You could use the first code block from my first post. I created a gist for it here: https://gist.github.com/hendrikstier/068b7e17fc4af18fcbf8

I will review my settings soon, but I'm pretty sure I set the tab size to 2 globally.

**Comment by Ennosuke** [comment]
With the provided gist I can reproduce the error, but I think it's a problem within Sublime and not only limited to the plugin. Currently the plugin only uses the function expand_tabs and unexpand_tabs provided by Sublime Text. Other than that it only sets the tab_size it may be that this is not working correctly if we have mixed tabs and spaces in one file.

I don't see a way yet to do otherwise without walking through the file line by line and do the replace by hand, which I think would be slower than what Sublime provides. But I'll look into it

**Comment by hendrikstier** [comment]
I just stumbled across the following: I moved to a computer without this plugin installed and discovered a command in the command palette names "Indentation: Reindent lines", which works with a unregularly indented file, that does _not_ mix tabs and spaces. If they are mixed, the number of spaces used in the result is incorrect. But when applying the conversion "Convert Tabs to Spaces" and then the reindent lines command, the outcome is as desired. Maybe we could chain the two commands?

**Comment by Ennosuke** [comment]
I added the command to the plugin. You can see the changes in the devel branch. I tested it with your file and it worked like it should, could you please test it yourself and give me feedback if it works? If so i'll merge it into the master.

Just a little edit: If Sublime thinks the file has already the right settings, the reindent does not work reliable, so I opted for not doing it then.
